{
    "dates":{
        "2020-03-22":{
            "countries":{
                "Afghanistan":{
                    "date":"2020-03-22",
                    "id":"afghanistan",
                    "links":[{"href":"/api/2020-03-22/country/afghanistan","rel":"self","type":"GET"}],
                    "name":"Afghanistan",
                    "name_es":"Afganist\u00e1n",
                    "name_it":"afghanistan",
                    "regions":[],
                    "source":"John Hopkins University",
                    "today_confirmed":40,
                    "today_deaths":1,
                    "today_new_confirmed":16,
                    "today_new_deaths":1,
                    "today_new_open_cases":15,
                    "today_new_recovered":0,
                    "today_open_cases":38,
                    "today_recovered":1,
                    "today_vs_yesterday_confirmed":0.6666666666666667,
                    "today_vs_yesterday_deaths":null,
                    "today_vs_yesterday_open_cases":0.6521739130434783,
                    "today_vs_yesterday_recovered":0.0,
                    "yesterday_confirmed":24,
                    "yesterday_deaths":0,
                    "yesterday_open_cases":23,
                    "yesterday_recovered":1
                },
                "Albania":{
                    "date":"2020-03-22",
                    "id":"albania",
                    "links":[{"href":"/api/2020-03-22/country/albania","rel":"self","type":"GET"}],
                    "name":"Albania",
                    "name_es":"Albania",
                    "name_it":"Albania",
                    "regions":[],
                    "source":"John Hopkins University",
                    "today_confirmed":89,
                    "today_deaths":2,
                    "today_new_confirmed":13,
                    "today_new_deaths":0,
                    "today_new_open_cases":13,
                    "today_new_recovered":0,
                    "today_open_cases":85,
                    "today_recovered":2,
                    "today_vs_yesterday_confirmed":0.17105263157894735,
                    "today_vs_yesterday_deaths":0.0,
                    "today_vs_yesterday_open_cases":0.18055555555555558,
                    "today_vs_yesterday_recovered":0.0,
                    "yesterday_confirmed":76,
                    "yesterday_deaths":2,
                    "yesterday_open_cases":72,
                    "yesterday_recovered":2
                };
            };
        };
    };
};